### ISSUE TITLE
After deleting the user from console also, I could able to connect messenger with same token id

### ISSUE THREAD

**Issue by pradeepsiluveru** [mesibo/messenger-javascript#10]
Im connecting messenger app with user token which is created in console , But after deleting same user from console and then trying to connect messenger I could able to connect and send messages to other user also.

Ideally should not be allowed to connect the messenger app . And users which are added in the same app should not be loaded.

Please help me in this scenario.

**Comment by mesibo** [comment]
Once tokens are deleted, users can't connect neither they can send messages. You are doing something wrong. 

For any help, read this https://mesibo.com/documentation/faq/support/#what-information-should-i-provide-when-requesting-technical-support

and this https://mesibo.com/documentation/faq/support/#can-you-help-with-messenger-whatsapp-clone-demo-and-ui-modules

Thread closed.
