### ISSUE TITLE
Calls not working, incorrect online/offline indicators, incorrect read receipts etc

### ISSUE THREAD

**Issue by sanmiguel2019** [mesibo/messenger-javascript#3]
New Js demo also has problems:

1) Calls are not working at all. I make a call but recipient never get it.

2) Read receipts are not working correctly. Read receipt should be sent when user really reads message, not when message has been delivered to the device.
For example, I send a message from PC to Js demo in mobile phone but mobile phone is not active. I immediately get the read receipt. I send a message from mob. phone to PC and I get read receipt even if the tab with chat is not active.

Similar issues I have seen in Android app. I don't know, probably it's fixed now.

Last summer I wrote a socket.io/nodejs chat and I use Page Visibility Api to detect message reads and it works perfectly in all devices. The reason why I want to integrate Mesibo yn my projects is that I need android and iOS apps.

3) The same problem with online/offline indicators. When mobile phone is not active or user switches between browser tabs/programs, "offline" should be sent immediately, not after some time as it happends in reality.

4) This errors appears in the console:
```
*** WARNING: mesibo requires secure(https) connection ***
(anonymous) @ mesibo.js:103
```
despite the fact that I am using https.

My question is:

Is there anyone who could help me to integrate Mesibo in my project - to modify this Js demo so that it works correctly?  I need also to add typing indicators, new messages numbers and to integrate it in my design etc. Of course, I would pay for it.

**Comment by mesibo** [comment]
We are unable to help without seeing your code. In any case, It won't give https warning unless you are not running https. Calls won't work without https. 

If you still having issues, file a ticket at https://mesibo.com/ticket and send us the URL of your code.

**Comment by sanmiguel2019** [comment]
Of course, I can open a ticket with real URL where I test the chat but look at my screenshot:

![mesibohttps](https://user-images.githubusercontent.com/54183931/80073068-13369700-853f-11ea-9e0f-857eaaa951e3.png)

I am using https but there is an error saying that mesibo requires https connection.

It's not my code - I just downloaded your Js examples and changed only const MESIBO_ACCESS_TOKEN, const MESIBO_APP_ID, const POPUP_DISPLAY_NAME and const POPUP_DESTINATION_USER

I needed a Js example that could easy integrate in my existing website (that already is using Jquery) and it's design, without touching the `<body>` tag, without bootstrap, etc, without learning things that I don't know as Angular, for example. Unfortunately, this example is made as a standalone chat, not for integration.

This example does not contain typing indicator, possibility to delete messages and bugs should be fixed in js example and in apps.

And as I wote, things like online/offline are working totally wrong. 
1. Two users access their conversation but none of them see that they are online.
2. User appears online only when starts typing a message.
3. I sent a message from user A to user B. User B reads the message and closes the browser. 35 minutes after that user A still sees that user B is online. Only after page reload the indicator "online" disappears for that user.

Read receipts also should be fixed. These things are very important because incorrect functioning of online/offline indicators and read receipts may cause misunderstandings between people.

**Comment by mesibo** [comment]
we do not see any issues. We will not further entertain any question from you without URL.
