### ISSUE TITLE
Features under implementation

### ISSUE THREAD

**Issue by thinkingheads** [mesibo/messenger-javascript#5]
Hello,

Could you give some date when "Features under implementation" will be implemented in your messenger-javascript?
We are in front of a choice between Mesibo and Tinode Messenger which is open sourse and free.
We would prefer Mesibo, but provided messenger-javascript lacks many important features and some features like read receipts and online status are not working correctly. If we need to hire a programmer for Mesibo javascript, it can be more expensive than adding features to Tinode.

**Comment by mesibo** [comment]
No dates, no timelines. Source code is for reference only, you can implement anything you like.
