### ISSUE TITLE
i have upgraded mesibo cloud to mesibo on-premise

### ISSUE THREAD

**Issue by chetan-the-dev** [mesibo/messenger-javascript#7]
i have upgraded mesibo cloud to on-premise but still i am not getting message entries in database can you tell me what more steps i need to do for effect this upgrade. on mesibo dashboard on-premise setting is looks ok and it's showing me Running Status on ok(host name)

**Comment by mesibo** [comment]
Not sufficient information for us to help. 

Refer to the on-premise section in http://mesibo.com/help to learn how to troubleshoot and request for the support.
