### ISSUE TITLE
How to fetch all the users listed in my application

### ISSUE THREAD

**Issue by pradeepsiluveru** [mesibo/messenger-javascript#9]
Hi Mesibo Team,

Currently I'm looking for the function which can fetch all the users from my application which is defined in console ex:XYZ .

Ex: my application name is - XYZ under this I listed some users from console or by API .
But in messenger screen I don't want to go and add all the users manually then chat, just by calling function should get the users for the particular application name ex XYZ and can list out in my messenger left panel.

Please help me in resolving this use case or issue.

Thank you, 
Pradeep

**Comment by mesibo** [comment]
You can modify the messenger to suit your needs. You can save users in your own database and download it as you like. 

On a side note, that's a very poor requirement, if you have a million users, will you download all?
